"""Generate HANDOFF.md - the document a collaborator reads before touching this repo.

The probe tables here are derived from the recorded inventory
(D:\\jepa_phase0\\autopilot_out\\p1_stats\\p1b_full_inventory.json) and from the
generated macro file. Narrative guidance is maintained separately and is not
a proof that every manuscript claim or numeric literal has been verified.

The point of this document is that a collaborator arriving with better runs can
tell, without asking, which numbers in the PDF are real, which are placeholders,
and exactly which artifact produced each one.
"""
import io
import json
import os
import re
from collections import defaultdict

REPO = r"C:\Users\Gary\Desktop\jepa"
PAPER = os.path.join(REPO, "paper", "genai4health2026")
INV = r"D:\jepa_phase0\autopilot_out\p1_stats\p1b_full_inventory.json"
OUT = os.path.join(REPO, "HANDOFF.md")


def main():
    inv = json.load(io.open(INV, encoding="utf-8"))
    recs = inv["records"]

    auto_path = os.path.join(PAPER, "auto", "auto_numbers.tex")
    auto = io.open(auto_path, encoding="utf-8").read()
    pending = sorted(set(re.findall(r"\\newcommand\{\\(\w+)\}\{\\ph\{pending\}\}", auto)))

    by_status = defaultdict(list)
    for r in recs:
        by_status[r.get("status", "unknown")].append(r)

    L = []
    w = L.append

    w("# Handoff: what is real, what is not, and how to replace it")
    w("")
    w("Generated by `autopilot/gen_handoff.py` from the verified probe inventory.")
    w("Do not edit by hand - rerun the generator instead, or it will drift.")
    w("")
    w("Inventory generated: %s" % inv.get("generated", "unknown"))
    w("")
    w("## Read this first")
    w("")
    w("The tables below identify saved prediction artifacts and their recorded status.")
    w("Many manuscript results are generated through")
    w("`paper/genai4health2026/auto/auto_numbers.tex`; protocol, geometry and")
    w("literature values also need explicit source review. A resolving macro is")
    w("not proof of a correct claim, and an old AUC is not a result of fixed code.")
    w("See `VERSION_BOARD.md` and `autopilot/investigations/delivered_task/BOARD.md`")
    w("for the current engineering and paper state.")
    w("")
    w("The release workflow after reviewing new or changed evidence:")
    w("")
    w("```")
    w("D:\\jepa_phase0\\.venv\\Scripts\\python.exe autopilot\\refresh_all.py")
    w("```")
    w("")
    w("Review the workflow's explicit coverage and asset manifest before publishing.")
    w("Externally produced figures are retained inputs unless their producer is")
    w("registered. Preserve the prior release if any required check fails.")
    w("Generated Word copies must also preserve collaborator edits and source references.")
    w("")

    w("## Placeholders currently in the paper")
    w("")
    if pending:
        w("These %d macros render in red with a dagger and are NOT measured." % len(pending))
        w("They are wired into the tables already, so supplying the underlying run")
        w("is sufficient - no LaTeX edit is needed.")
        w("")
        for p in pending:
            w("- `\\%s`" % p)
    else:
        w("No red pending macros detected by this inventory helper.")
        w("This is not a claim that every macro is measured: explicit `not run`")
        w("and dash markers, such as the corrected-COVER slot, remain non-results.")
    w("")

    w("## Every probe behind the paper")
    w("")
    w("`status` meanings:")
    w("")
    w("- **primary** - cited in the paper as a result")
    w("- **retracted** - measured, then withdrawn as invalid; never cite")
    w("- **excluded** - measured but disqualified from headline comparisons")
    w("")

    order = ["primary", "retracted", "excluded"]
    for st in order + [s for s in by_status if s not in order]:
        rows = by_status.get(st)
        if not rows:
            continue
        w("### status: %s (%d)" % (st, len(rows)))
        w("")
        w("| arm | epoch | precision | test AUC | source artifact |")
        w("|---|---|---|---|---|")
        for r in sorted(rows, key=lambda x: (str(x.get("arm")), x.get("epoch") or 0)):
            auc = r.get("auc")
            auc_s = "%.6f" % auc if isinstance(auc, (int, float)) else "n/a"
            w("| %s | %s | %s | %s | `%s` |" % (
                r.get("arm"), r.get("epoch"), r.get("precision"), auc_s, r.get("path")))
        w("")

    ex = inv.get("exclusions")
    if ex:
        w("## Why the excluded and retracted runs were disqualified")
        w("")
        if isinstance(ex, dict):
            for k, v in ex.items():
                w("- **%s**: %s" % (k, v))
        elif isinstance(ex, list):
            for e in ex:
                w("- %s" % e)
        w("")

    w("## Adding your own runs")
    w("")
    w("### Priority: the corrected COVER arm")
    w("")
    w("A corrected comparative run is subsequent work requiring approval. The historical")
    w("`cover-f021` arm never realised the coverage it was configured for: the")
    w("collator truncates every predictor target to the shortest in the microbatch")
    w("AFTER the sampler has chosen placement, changing the delivered task.")
    w("Use the versioned real-data diagnostic rather than unscoped geometry values.")
    w("The original account is in")
    w("`autopilot/COVER_AUDIT.md`.")
    w("")
    w("What a corrected run needs:")
    w("")
    w("1. Score and enforce coverage against the prefix-truncated shapes that")
    w("   actually reach the model, not the full rectangles. The truncation is at")
    w("   `src/masks/curriculum.py`, the `global_min_pred` branch.")
    w("2. Measure targets and actual encoder context AFTER collation, with explicit")
    w("   counters for infeasible constraints and random/background supervision.")
    w("3. Restart from the shared epoch-25 ancestor. Patching mid-trajectory would")
    w("   splice two masking policies into one curve. Do not start sustained training")
    w("   merely to complete the workshop: retain valid historical evidence and")
    w("   label the corrected comparison as future work when unrun.")
    w("")
    w("Where to put the results:")
    w("")
    w("```")
    w("D:\\jepa_phase0\\runs\\frozen_meanpool_coverfix_ep<N>\\test_predictions.npz")
    w("```")
    w("")
    w("Then run `refresh_all.py`. The paper has an inert slot for this: the macros")
    w("`\\AUCCoverFixed*` and `\\CoverFixedStatus` currently render `---` and")
    w("`not run`, and the appendix states plainly that the over-coverage question")
    w("is OPEN. A new result needs explicit lineage, status, source mapping and")
    w("an independently reviewed interpretation before those entries can change.")
    w("")
    w("### Any other run")
    w("")
    w("The inventory discovers probes by scanning run directories for saved")
    w("per-case test predictions. Follow the existing naming convention visible in")
    w("the tables above, for example:")
    w("")
    w("```")
    w("D:\\jepa_phase0\\runs\\frozen_meanpool_<arm>_ep<N>\\test_predictions.npz")
    w("```")
    w("")
    w("Confirm that the inventory recognizes the new arm, epoch and precision,")
    w("and that the required source mapping is complete before invoking refresh.")
    w("")
    w("Two required interpretation rules:")
    w("")
    w("1. Comparisons must be epoch- and precision-matched unless a separately")
    w("   labeled sensitivity analysis explicitly studies that difference.")
    w("2. No arm's numbers may ever be reported under another arm's name. Each")
    w("   AUC stays bound to the artifact that produced it, listed above.")
    w("")

    w("## Known open questions")
    w("")
    w("- The `cover-f021` arm rises to a peak at epoch 73 and then declines, ending")
    w("  below the random null at epoch 100. See `autopilot/COVER_AUDIT.md` for the")
    w("  investigation into whether this is a genuine result or an implementation")
    w("  defect. If you have corrected COVER runs, this is the arm to replace.")
    w("- Measured mask geometry (600 slices) reports that `envelope` hides more")
    w("  anatomy than `cover` while keeping less context, which inverts COVER's")
    w("  design intent. The audit covers this discrepancy.")
    w("- Each reported policy has one completed pretraining continuation. There")
    w("  is no completed continuation-level replication result. The earlier")
    w("  probe-seed variance claim is not supported by retained repeat artifacts.")
    w("")

    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("wrote %s" % OUT)
    print("  probes: %d | pending macros: %d" % (len(recs), len(pending)))
    for st in sorted(by_status):
        print("  %-12s %d" % (st, len(by_status[st])))


if __name__ == "__main__":
    main()
