"""Generate HANDOFF.md - the document a collaborator reads before touching this repo.

Everything here is derived from the verified inventory
(D:\\jepa_phase0\\autopilot_out\\p1_stats\\p1b_full_inventory.json) and from the
generated macro file, so the handoff cannot drift away from what the paper
actually claims. Nothing in the output is typed by hand.

The point of this document is that a collaborator arriving with better runs can
tell, without asking, which numbers in the PDF are real, which are placeholders,
and exactly which artifact produced each one.
"""
import io
import json
import os
import re
from collections import defaultdict

REPO = r"C:\Users\Gary\Desktop\jepa"
PAPER = os.path.join(REPO, "paper", "genai4health2026")
INV = r"D:\jepa_phase0\autopilot_out\p1_stats\p1b_full_inventory.json"
OUT = os.path.join(REPO, "HANDOFF.md")


def main():
    inv = json.load(io.open(INV, encoding="utf-8"))
    recs = inv["records"]

    auto_path = os.path.join(PAPER, "auto", "auto_numbers.tex")
    auto = io.open(auto_path, encoding="utf-8").read()
    pending = sorted(set(re.findall(r"\\newcommand\{\\(\w+)\}\{\\ph\{pending\}\}", auto)))

    by_status = defaultdict(list)
    for r in recs:
        by_status[r.get("status", "unknown")].append(r)

    L = []
    w = L.append

    w("# Handoff: what is real, what is not, and how to replace it")
    w("")
    w("Generated by `autopilot/gen_handoff.py` from the verified probe inventory.")
    w("Do not edit by hand - rerun the generator instead, or it will drift.")
    w("")
    w("Inventory generated: %s" % inv.get("generated", "unknown"))
    w("")
    w("## Read this first")
    w("")
    w("Every number in the manuscript resolves through a LaTeX macro in")
    w("`paper/genai4health2026/auto/auto_numbers.tex`, which is regenerated from")
    w("saved per-case test predictions. No number is typed into the prose. That")
    w("means you can replace an experiment and the entire paper - text, tables,")
    w("figures - updates itself.")
    w("")
    w("To regenerate everything after adding or replacing a run:")
    w("")
    w("```")
    w("D:\\jepa_phase0\\.venv\\Scripts\\python.exe autopilot\\refresh_all.py")
    w("```")
    w("")
    w("That rebuilds macros, tables, figures, the PDF, and the validated Overleaf")
    w("ZIP. `autopilot/check_manuscript.py` runs as a gate and fails the build on")
    w("undefined macros, dangling references, banned phrases, or hand-typed numbers.")
    w("")

    w("## Placeholders currently in the paper")
    w("")
    if pending:
        w("These %d macros render in red with a dagger and are NOT measured." % len(pending))
        w("They are wired into the tables already, so supplying the underlying run")
        w("is sufficient - no LaTeX edit is needed.")
        w("")
        for p in pending:
            w("- `\\%s`" % p)
    else:
        w("None. Every macro in the paper currently resolves to a measured value.")
    w("")

    w("## Every probe behind the paper")
    w("")
    w("`status` meanings:")
    w("")
    w("- **primary** - cited in the paper as a result")
    w("- **retracted** - measured, then withdrawn as invalid; never cite")
    w("- **excluded** - measured but disqualified from headline comparisons")
    w("")

    order = ["primary", "retracted", "excluded"]
    for st in order + [s for s in by_status if s not in order]:
        rows = by_status.get(st)
        if not rows:
            continue
        w("### status: %s (%d)" % (st, len(rows)))
        w("")
        w("| arm | epoch | precision | test AUC | source artifact |")
        w("|---|---|---|---|---|")
        for r in sorted(rows, key=lambda x: (str(x.get("arm")), x.get("epoch") or 0)):
            auc = r.get("auc")
            auc_s = "%.6f" % auc if isinstance(auc, (int, float)) else "n/a"
            w("| %s | %s | %s | %s | `%s` |" % (
                r.get("arm"), r.get("epoch"), r.get("precision"), auc_s, r.get("path")))
        w("")

    ex = inv.get("exclusions")
    if ex:
        w("## Why the excluded and retracted runs were disqualified")
        w("")
        if isinstance(ex, dict):
            for k, v in ex.items():
                w("- **%s**: %s" % (k, v))
        elif isinstance(ex, list):
            for e in ex:
                w("- %s" % e)
        w("")

    w("## Adding your own runs")
    w("")
    w("The inventory discovers probes by scanning run directories for saved")
    w("per-case test predictions. Follow the existing naming convention visible in")
    w("the tables above, for example:")
    w("")
    w("```")
    w("D:\\jepa_phase0\\runs\\frozen_meanpool_<arm>_ep<N>\\test_predictions.npz")
    w("```")
    w("")
    w("Then run `refresh_all.py`. The new probe is picked up automatically, enters")
    w("the inventory, and any macro it satisfies stops rendering as a placeholder.")
    w("")
    w("Two rules the build enforces, so you do not have to remember them:")
    w("")
    w("1. Comparisons are epoch-matched and precision-matched. A probe compared")
    w("   across mismatched epochs or precisions is rejected, not silently used.")
    w("2. No arm's numbers may ever be reported under another arm's name. Each")
    w("   AUC stays bound to the artifact that produced it, listed above.")
    w("")

    w("## Known open questions")
    w("")
    w("- The `cover-f021` arm rises to a peak at epoch 73 and then declines, ending")
    w("  below the random null at epoch 100. See `autopilot/COVER_AUDIT.md` for the")
    w("  investigation into whether this is a genuine result or an implementation")
    w("  defect. If you have corrected COVER runs, this is the arm to replace.")
    w("- Measured mask geometry (600 slices) reports that `envelope` hides more")
    w("  anatomy than `cover` while keeping less context, which inverts COVER's")
    w("  design intent. The audit covers this discrepancy.")
    w("- Each policy was pretrained once. Probe-seed variation is bounded at")
    w("  0.0003 to 0.0018, but those are technical replicates, not independent")
    w("  pretraining runs. This is the study's principal limitation.")
    w("")

    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("wrote %s" % OUT)
    print("  probes: %d | pending macros: %d" % (len(recs), len(pending)))
    for st in sorted(by_status):
        print("  %-12s %d" % (st, len(by_status[st])))


if __name__ == "__main__":
    main()
