"""Render diagnostic macros from fixed, source-bound engineering evidence."""

import hashlib
import json
from pathlib import Path

if __package__:
    from .numeric_bindings import Evidence, fmt, operation, ref
else:
    from numeric_bindings import Evidence, fmt, operation, ref


ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper" / "genai4health2026"
EVIDENCE = ROOT / "autopilot" / "investigations" / "delivered_task" / "evidence"


def render():
    paths = {
        "delivered_full_batches": EVIDENCE / "mask_replay600_v2" / "full_batch64_confirmation.json",
        "delivered_gpu_joint": EVIDENCE / "training_gpu_guided_v1" / "joint_summary.json",
    }
    sources = {
        name: {
            "root": "repo",
            "path": path.relative_to(ROOT).as_posix(),
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        }
        for name, path in paths.items()
    }
    expressions = {}

    def count(name, policy, field):
        expressions[name] = fmt("%d", ref("delivered_full_batches", policy, field))

    def percent(name, policy, field):
        expressions[name] = fmt(
            "%.2f", operation("percent", ref("delivered_full_batches", policy, field))
        )

    count("DTFullImages", "cover_legacy", "full_batch_images")
    count("DTValidGuides", "cover_legacy", "valid")
    count("DTTissueTruncation", "cover_legacy", "target_tissue_truncation_losses")
    count("DTZeroContext", "cover_legacy", "zero_tissue_context")
    for prefix, policy in (
        ("DTLegacy", "cover_legacy"),
        ("DTPrefix", "cover_v2"),
        ("DTGuard", "cover_v2_guard"),
    ):
        count(prefix + "FloorMiss", policy, "valid_floor_misses")
        count(prefix + "Truncation", policy, "target_tissue_truncation_losses")
        count(prefix + "ZeroContext", policy, "zero_tissue_context")
        percent(prefix + "ScoredMass", policy, "mean_scored_mass")
        percent(prefix + "DeliveredMass", policy, "mean_delivered_mass")
        expressions[prefix + "ContextMean"] = fmt(
            "%.2f", ref("delivered_full_batches", policy, "mean_context_tissue")
        )
    expressions["DTGPUObservations"] = fmt(
        "%d", ref("delivered_gpu_joint", "observations")
    )
    expressions["DTGPUCases"] = fmt(
        "%d", operation("length", ref("delivered_gpu_joint", "policies"))
    )
    expressions["DTGPUGuardChanges"] = fmt(
        "%d", ref("delivered_gpu_joint", "guard_modified_images")
    )

    evidence = Evidence(PAPER, EVIDENCE, sources)
    lines = ["% Generated by autopilot/make_delivered_assets.py; do not edit values."]
    for name, expression in expressions.items():
        lines.append(r"\newcommand{\%s}{%s}" % (name, evidence.evaluate(expression)))
    (PAPER / "auto" / "delivered_numbers.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
    bindings = {
        "version": 1,
        "sources": sources,
        "macros": {name: {"expression": expression} for name, expression in expressions.items()},
        "scope": "Fixed engineering diagnostics, not downstream AUC or independent training replicates",
    }
    (EVIDENCE / "delivered_numeric_bindings.json").write_text(
        json.dumps(bindings, indent=2) + "\n", encoding="utf-8"
    )
    print("Rendered", len(expressions), "source-bound diagnostic macros")
    return bindings


if __name__ == "__main__":
    render()
