"""Verify that every cited reference is a real paper, not a hallucinated one.

NeurIPS 2026's LLM policy names exactly one sanctionable authoring behaviour:
"using references generated by an LLM without conducting the due diligence to
verify correctness, existence and appropriateness".  The penalty is revocation
of publication status, at any time, including after acceptance.

check_manuscript.py already reports "0 missing citations", but that only
confirms a \\cite key resolves to a BibTeX entry.  A fabricated entry has both
a key and a record, so it passes that check.  This resolves each identifier
against the issuing authority instead: arXiv's API for eprints, Crossref for
DOIs.  Only public bibliographic metadata is sent, which is what those
services exist to serve.

Usage:
    python autopilot/verify_citations.py            # offline identifier audit
    python autopilot/verify_citations.py --online   # also resolve each one
"""

import argparse
import json
import re
import sys
import time
import urllib.parse
import urllib.request

sys.stdout.reconfigure(encoding="utf-8")

TEX = "paper/genai4health2026/main_submission.tex"
BIB = "paper/genai4health2026/references.bib"
UA = {"User-Agent": "citation-verifier/1.0 (academic reference check)"}


def cited_keys(tex):
    keys = set()
    for m in re.finditer(r"\\cite[a-zA-Z]*\*?(?:\[[^\]]*\])*\{([^}]*)\}", tex):
        keys.update(k.strip() for k in m.group(1).split(",") if k.strip())
    return keys


def bib_entries(bib):
    out = {}
    for m in re.finditer(r"@(\w+)\s*\{\s*([^,]+),", bib):
        start = m.end()
        depth, i = 1, bib.index("{", m.start())
        i += 1
        while i < len(bib) and depth:
            if bib[i] == "{":
                depth += 1
            elif bib[i] == "}":
                depth -= 1
            i += 1
        out[m.group(2).strip()] = (m.group(1).lower(), bib[start:i])
    return out


def field(body, name):
    m = re.search(name + r"\s*=\s*[{\"](.*?)[}\"]\s*,?\s*\n", body, re.S | re.I)
    return re.sub(r"\s+", " ", m.group(1)).strip() if m else None


def identifier(body):
    doi = field(body, "doi")
    if doi:
        doi = doi.strip()
        # arXiv mints DataCite DOIs of the form 10.48550/arXiv.2310.02492.
        # Crossref does not serve those, so resolve them at arXiv instead.
        m = re.match(r"^10\.48550/arxiv\.(.+)$", doi, re.I)
        if m:
            return "arxiv", m.group(1)
        return "doi", doi
    eprint = field(body, "eprint") or field(body, "archiveprefix")
    if eprint and re.match(r"^\d{4}\.\d{4,5}", eprint.strip()):
        return "arxiv", eprint.strip()
    url = field(body, "url") or ""
    m = re.search(r"arxiv\.org/abs/([\d.]+)", url)
    if m:
        return "arxiv", m.group(1)
    m = re.search(r"doi\.org/(10\.[^\s}]+)", url)
    if m:
        return "doi", m.group(1)
    if url:
        return "url", url
    return None, None


def search_arxiv_title(title):
    """Find a paper by title when the entry carries no usable identifier."""
    clean = re.sub(r"[{}\\$]", "", title or "")
    clean = re.sub(r"[^A-Za-z0-9 :\-]", " ", clean)
    clean = re.sub(r"\s+", " ", clean).strip()
    if not clean:
        return None
    q = ("http://export.arxiv.org/api/query?search_query=ti:"
         + urllib.parse.quote('"%s"' % clean) + "&max_results=3")
    try:
        with urllib.request.urlopen(urllib.request.Request(q, headers=UA),
                                    timeout=25) as r:
            x = r.read().decode("utf-8", "replace")
    except Exception:
        return None
    hits = re.findall(r"<entry>.*?<title>(.*?)</title>", x, re.S)
    for h in hits:
        h = re.sub(r"\s+", " ", h).strip()
        a, b = norm(clean), norm(h)
        if a and b and (a in b or b in a):
            return h
    return None


def resolve_arxiv(aid):
    q = f"http://export.arxiv.org/api/query?id_list={urllib.parse.quote(aid)}"
    with urllib.request.urlopen(urllib.request.Request(q, headers=UA), timeout=25) as r:
        x = r.read().decode("utf-8", "replace")
    if "<entry>" not in x:
        return None
    m = re.search(r"<entry>.*?<title>(.*?)</title>", x, re.S)
    return re.sub(r"\s+", " ", m.group(1)).strip() if m else None


def resolve_doi(doi):
    q = "https://api.crossref.org/works/" + urllib.parse.quote(doi, safe="")
    try:
        with urllib.request.urlopen(urllib.request.Request(q, headers=UA), timeout=25) as r:
            d = json.load(r)
    except Exception:
        return None
    t = d.get("message", {}).get("title") or []
    return t[0] if t else None


def norm(s):
    return re.sub(r"[^a-z0-9]+", " ", (s or "").lower()).strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--online", action="store_true")
    args = ap.parse_args()

    tex = open(TEX, encoding="utf-8").read()
    bib = open(BIB, encoding="utf-8").read()
    keys = sorted(cited_keys(tex))
    ents = bib_entries(bib)

    print(f"cited keys : {len(keys)}")
    print(f"bib entries: {len(ents)}")
    missing = [k for k in keys if k not in ents]
    if missing:
        print(f"MISSING FROM BIB: {missing}")

    rows, no_id = [], []
    for k in keys:
        if k not in ents:
            continue
        kind, val = identifier(ents[k][1])
        title = field(ents[k][1], "title")
        rows.append((k, kind, val, title))
        if kind in (None, "url"):
            no_id.append((k, kind, title))

    print(f"\nwith a resolvable identifier (doi/arxiv): "
          f"{sum(1 for r in rows if r[1] in ('doi', 'arxiv'))}/{len(rows)}")
    if no_id:
        print(f"\nNO RESOLVABLE IDENTIFIER ({len(no_id)}) "
              f"- these need manual eyeball verification:")
        for k, kind, title in no_id:
            print(f"   {k:28s} [{kind or 'none'}] {(title or '')[:64]}")

    if not args.online:
        print("\n(run with --online to resolve each identifier)")
        return 0

    print("\nresolving against arXiv / Crossref ...")
    bad, ok, skipped = [], 0, 0
    for k, kind, val, title in rows:
        if kind == "arxiv":
            got = resolve_arxiv(val)
        elif kind == "doi":
            got = resolve_doi(val)
        else:
            got = search_arxiv_title(title)
            time.sleep(0.35)
            if got:
                ok += 1
                print(f"  found by title  {k:24s} -> {got[:58]}")
            else:
                skipped += 1
                print(f"  NEEDS EYEBALL   {k:24s} {(title or '')[:52]}")
            continue
        time.sleep(0.35)
        if got is None:
            bad.append((k, kind, val, title, "DID NOT RESOLVE"))
            print(f"  UNRESOLVED  {k:26s} {kind}:{val}")
            continue
        a, b = norm(title), norm(got)
        if a and b and (a in b or b in a or
                        len(set(a.split()) & set(b.split())) >= max(2, len(a.split()) // 2)):
            ok += 1
        else:
            bad.append((k, kind, val, title, got))
            print(f"  TITLE MISMATCH {k}\n      bib: {title}\n      src: {got}")

    print(f"\nresolved and title-matched : {ok}")
    print(f"could not check (no id)    : {skipped}")
    print(f"PROBLEMS                   : {len(bad)}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
